In [3]:
import tensorflow as tf

In [4]:
x = tf.range(10) ## any data tensor
dataset = tf.data.Dataset.from_tensor_slices(x)
# show type of dataset?
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [5]:
for item in dataset:
  print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


## Chaining Transformations
- applying transformations to the dataset for manipulation

In [6]:
dataset = dataset.repeat(3).batch(7)
for item in dataset:
  print(item)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
tf.Tensor([8 9], shape=(2,), dtype=int32)


In [10]:
dataset = dataset.map(lambda x: x*2)
# following line will have a deprecated asset for unbatch
# dataset = dataset.apply(tf.data.experimental.unbatch() ) 

### microcontroller audio ai assistant translator WITH AR glasses to display the text

ValueError: ignored

## Shuffling the Dataset


In [11]:
dataset = tf.data.Dataset.range(10).repeat(3)
dataset = dataset.shuffle(buffer_size=5, seed=42).batch(7)
#for loop to print items in the dataset that uses tensors to hold data
for item in dataset:
  print(item)

tf.Tensor([0 2 3 6 7 9 4], shape=(7,), dtype=int64)
tf.Tensor([5 0 1 1 8 6 5], shape=(7,), dtype=int64)
tf.Tensor([4 8 7 1 2 3 0], shape=(7,), dtype=int64)
tf.Tensor([5 4 2 7 8 9 9], shape=(7,), dtype=int64)
tf.Tensor([3 6], shape=(2,), dtype=int64)


In [ ]:
# repeat() - on a shuffled dataset will generate a new order at every iteration
# can set reshuffle_each_iteration=False

## Interleaving Lines from Multiple Files